import { Metadata } from "next";
import Link from "next/link";
import { Fragment, PropsWithChildren } from "react";
import Navigation from "./navigation";

export const metadata: Metadata = {
  title: "winci.dev",
  description: "Generated by create next app",
};

export default function Layout({ children }: PropsWithChildren) {
  return (
    <Fragment>
      <div className="relative flex h-full w-full">
        <Navigation />
        <div className="bg-grid flex w-full items-center justify-center overflow-hidden">
          {children}
        </div>
      </div>
    </Fragment>
  );
}
