import { Metadata } from "next";
import { Fragment, PropsWithChildren } from "react";
import Navigation from "./navigation";

export const metadata: Metadata = {
  title: "winci.dev",
  description: "Generated by create next app",
};

export default function Layout({ children }: PropsWithChildren) {
  return (
    <div className="bg-grid h-full w-full">
      <div className="relative flex h-full w-full">
        <Navigation />
        <div className="flex w-full overflow-hidden">
          {children}
        </div>
      </div>
    </div>
  );
}
