import type { Metadata } from "next";
import Navigation from "./navigation";

export const metadata: Metadata = {
  title: "winci.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navigation />
      <div className='flex flex-col flex-auto overflow-auto'>
        <main className="min-h-screen bg-slate-700">
          {children}
        </main>
      </div>
    </>
  );
}
