import { Metadata } from "next";
import React from "react";
import LoginForm from "./loginForm";
import { LoginFormFields } from "./components";
import { BackgroundBeams } from "@/components/backgroundBeams";

export const metadata: Metadata = {
  title: "winci.dev",
  description: "Generated by create next app",
};

async function Page() {
  return (
    <div className="relative flex h-screen flex-col items-center justify-center bg-neutral-950 antialiased">
      <div className="mx-auto max-w-2xl p-4">
        <LoginForm>
          <LoginFormFields />
        </LoginForm>
      </div>
      <BackgroundBeams />
    </div>
  );
}

export default Page;
