import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-row h-dvh overflow-x-hidden overflow-y-hidden bg-black'>
          <Navigation />
          <div className='flex flex-col flex-auto overflow-auto'>
            <main className="min-h-screen bg-slate-700">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
