import { Metadata } from "next";
import React, { Fragment } from "react";
import LoginForm from "./loginForm";
import { LoginFormFields } from "./components";
import { getSession } from "@/libs/auth";

export const metadata: Metadata = {
  title: "winci.dev",
  description: "Generated by create next app",
};

async function Page() {
  const session = await getSession();

  return (
    <Fragment>
      <div className="flex min-h-full min-w-full flex-col items-center justify-center overflow-hidden bg-gray-950">
        <div
          className={`absolute z-0 rounded-full bg-gradient-eclips2 from-blue-600 to-indigo-900 p-36 blur-xl filter hover:[animation-play-state:paused] motion-safe:animate-spin-slow md:p-56`}
        />
        <div className="absolute z-10 rounded-full bg-gray-950 p-32 md:p-52" />
        <LoginForm>
          <LoginFormFields />
        </LoginForm>
        <pre className="z-10">{JSON.stringify(session, null, 4)}</pre>
      </div>
    </Fragment>
  );
}

export default Page;
