
import { Metadata } from 'next';
import React from 'react'
import Content from './content';

export const metadata: Metadata = {
  title: "winci.dev",
  description: "Generated by create next app",
};

function Page() {
  return (
    <Content />
  )
}

export default Page